services:
  - type: web
    name: behavior-marketplace-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: behavior-marketplace-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://behavior-marketplace.vercel.app

databases:
  - name: behavior-marketplace-db
    databaseName: behavior_marketplace
    user: behavior_user
